import React, { useState, useEffect } from 'react';
import GaugeCard from './components/GaugeCard';
import AlertBanner from './components/AlertBanner';
import ReservoirCard from './components/ReservoirCard';
import FishingConditions from './components/FishingConditions';
import FishingReference from './components/FishingReference';
import WeatherForecast from './components/WeatherForecast';
import CommunityBar from './components/CommunityBar';

import logoUrl from './assets/logo-32.png';

// In production, this JSON is generated by the Python scraper and served
// from GitHub Pages as a static file. During dev, we import it directly.
const DATA_URL = import.meta.env.DEV
  ? new URL('./data/river-data.json', import.meta.url).href
  : `${import.meta.env.BASE_URL}data/river-data.json`;

function formatUpdatedAt(isoStr) {
  if (!isoStr) return '';
  try {
    const d = new Date(isoStr);
    const now = new Date();
    const diffMs = now - d;
    const diffMin = Math.floor(diffMs / 60000);

    if (diffMin < 1) return 'Just now';
    if (diffMin < 60) return `${diffMin}m ago`;
    if (diffMin < 1440) return `${Math.floor(diffMin / 60)}h ago`;

    return d.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
    });
  } catch {
    return '';
  }
}

// In production, this JSON is generated by the Python scraper and served

export default function App() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch(DATA_URL)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((json) => {
        setData(json);
        setLoading(false);
      })
      .catch((err) => {
        console.error('Failed to load river data:', err);
        setError(err.message);
        setLoading(false);
      });
  }, []);

  if (loading) {
    return (
      <div className="widget-container">
        <div className="loading-state">
          <div className="loading-state__spinner" />
          <div className="loading-state__text">Loading river conditions…</div>
        </div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="widget-container">
        <div className="error-state">
          Unable to load river data. Please try again later.
        </div>
      </div>
    );
  }

  // Filter to gauges with current data, then sort: flooding/elevated first
  const hasData = (g) =>
    g.current?.gage_height_ft != null || g.current?.streamflow_cfs != null;
  const statusOrder = { major: 0, moderate: 1, minor: 2, action: 3, normal: 4 };
  const sortedGauges = [...data.gauges]
    .filter(hasData)
    .sort(
      (a, b) =>
        (statusOrder[a.flood_status] ?? 4) - (statusOrder[b.flood_status] ?? 4)
    );

  const activeCount = sortedGauges.length;

  return (
    <div className="widget-container">
      {/* Chrome Bar */}
      <div className="chrome-bar">
        <a
          className="chrome-bar__brand"
          href="https://wausaupilotandreview.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          <img className="chrome-bar__logo-img" src={logoUrl} alt="Wausau Pilot & Review" />
          <span className="chrome-bar__logo">Wausau Pilot & Review</span>
          <span className="chrome-bar__divider" />
          <span className="chrome-bar__section-name">River Conditions</span>
        </a>
        <span className="chrome-bar__updated">
          {formatUpdatedAt(data.generated_at)}
        </span>
      </div>

      {/* Sponsor Strip */}
      <div className="sponsor-strip">
        Brought to you by <strong>Your Sponsor Here</strong> — Serving Central Wisconsin
      </div>

      {/* Weather Forecast */}
      <WeatherForecast forecast={data.weather_forecast} />

      {/* Alerts */}
      <AlertBanner alerts={data.alerts} />

      {/* Stream Gauges */}
      <div className="section-header">
        <h2 className="section-header__title">Stream Gauges</h2>
        <span className="section-header__subtitle">
          {activeCount} of {data.gauges.length} reporting · Marathon County
        </span>
      </div>

      <div className="gauges-grid">
        {sortedGauges.map((gauge) => (
          <GaugeCard key={gauge.id} gauge={gauge} />
        ))}
      </div>

      {/* Fishing Conditions */}
      {data.fishing_conditions && (
        <>
          <div className="section-header" style={{ marginTop: 'var(--space-lg)' }}>
            <h2 className="section-header__title">Fishing Conditions</h2>
            <span className="section-header__subtitle">
              Wausau area · updated every 30 min
            </span>
          </div>
          <FishingConditions conditions={data.fishing_conditions} />
        </>
      )}

      {/* Reservoirs */}
      {data.reservoirs && data.reservoirs.length > 0 && (
        <>
          <div className="section-header" style={{ marginTop: 'var(--space-lg)' }}>
            <h2 className="section-header__title">Reservoirs</h2>
            <span className="section-header__subtitle">
              {data.reservoirs.filter((r) => r.has_data).length} of{' '}
              {data.reservoirs.length} reporting · WVIC System
            </span>
          </div>

          <div className="reservoirs-grid">
            {data.reservoirs.filter((r) => r.has_data).map((reservoir) => (
              <ReservoirCard key={reservoir.slug} reservoir={reservoir} />
            ))}
          </div>
        </>
      )}

      {/* Fishing Guide */}
      <FishingReference gauges={data.gauges} />

      {/* Community */}
      <CommunityBar links={data.community_links} />

      {/* Footer */}
      <footer className="widget-footer">
        <div className="widget-footer__sources">
          Data from{' '}
          <a href="https://waterservices.usgs.gov/" target="_blank" rel="noopener noreferrer">
            USGS Water Services
          </a>
          {' · '}
          <a href="https://api.weather.gov/" target="_blank" rel="noopener noreferrer">
            National Weather Service
          </a>
          {' · '}
          <a href="https://wvic.com/" target="_blank" rel="noopener noreferrer">
            WVIC
          </a>
          {' · '}
          <a href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer">
            Open-Meteo
          </a>
          {' · '}
          <a href="https://solunar.org/" target="_blank" rel="noopener noreferrer">
            Solunar
          </a>
        </div>
        <div className="widget-footer__disclaimer">
          Data is provisional and subject to revision. Always consult official sources
          for safety decisions. Do not drive through flooded areas.
        </div>
      </footer>
    </div>
  );
}
